config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_scope :user do
    get 'users/two_factor_authentication' => 'users/sessions#two_factor_authentication', as: :two_factor_authentication
    get 'users/two_factor_setup' => 'users/registrations#two_factor_setup', as: :two_factor_setup
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :employees do
    resources :tasks, only: [:new, :create, :edit, :update]
  end
    
  get 'employee_dashboard', to: 'dashboards#employee'
  get 'hr_manager_dashboard', to: 'dashboards#hr_manager'
  
  root 'dashboards#redirect_based_on_role'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee Onboarding Portal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true %>
  </head>

  <body>
    <nav class = "nav">
      <% if user_signed_in? %>
        <%= link_to 'Dashboard', current_user.hr_manager? ? hr_manager_dashboard_path : employee_dashboard_path %>
        <%= link_to 'Log out', users_sign_out_path, method: :get %>
      <% else %>
        <%= link_to 'Log in', new_user_session_path %>
        <%= link_to 'Sign up', new_user_registration_path %>
      <% end %>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>